#!/bin/sh

# https://github.com/DAFF0D11/dafmenu

RAW_LIST=$(wmctrl -l)
WINDOW_ID=$(echo "$RAW_LIST" | cut -d ' ' -f1 )
WINDOW_TITLE=$(echo "$RAW_LIST" | cut -d ' ' -f5-)

LIST=$(
pr -2 -t -s <<eof
$WINDOW_TITLE
$WINDOW_ID
eof
)

dmenu_cmd(){
    ../dmenu -c -l 30 -ex 'ctrl-x,ctrl-g'
}

cut_choice(){
    echo "$1" | tail -n +2 | cut -f2
}

COMMAND=dmenu_cmd

CHOICE=$(echo "$LIST" | "$COMMAND")

[ -z "$CHOICE" ] && exit 0

case "$CHOICE" in
    ctrl-g*) cut_choice "$CHOICE" | xargs -I %% wmctrl -i -R %% ;;
    ctrl-x*) cut_choice "$CHOICE" | xargs -I %% wmctrl -i -c %% ;;
    *) wmctrl -i -a "$(cut_choice "$CHOICE")";;
esac
